# Generated by Django 4.2 on 2023-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(default='sad.jpg', upload_to='profile_pics'),
        ),
    ]
